name: text_recognition_flutter
description: A sample Flutter project that use text recognition.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  image_picker: ^0.8.6+2
  google_ml_kit: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
